name: dice_app2
description: A new Flutter project.
publish_to: 'none'
version: 1.1.1+3

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  url_launcher: ^6.1.10
  shake: ^2.2.0
  provider: ^6.0.5
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
